name: PoolApp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  http: ^1.2.2
  intl: ^0.20.2                      # 🔧 aggiornato per compatibilità con flutter_localizations
  image: ^4.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  calendar_date_picker2: ^2.0.1
  flutter_localizations:            # ✅ necessario per DatePicker/MaterialLocalizations
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/PA.png
    - assets/images/poolBG.jpg
    - assets/images/profile man.png
    - assets/images/profile women.png
    - assets/images/logo.png
