name: PoolApp
description: "A new Flutter project."
publish_to: 'none'

# VERSIONE AGGIORNATA
version: 1.0.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  http: ^1.2.2
  intl: ^0.20.2
  image: ^4.4.0
  flutter_riverpod: ^2.6.1
  calendar_date_picker2: ^2.0.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  firebase_messaging: ^15.2.6
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  firebase_remote_config: ^5.4.4
  package_info_plus: ^8.3.0
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/PA.png
    - assets/images/poolBG.jpg
    - assets/images/profile man.png
    - assets/images/profile women.png
    - assets/images/logo.png
