// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlciHDHkPqzO1k71z3zgqDiGISK7M11Fo',
    appId: '1:457062956823:web:73a2352ccd5b914e170152',
    messagingSenderId: '457062956823',
    projectId: 'poolschdule',
    authDomain: 'poolschdule.firebaseapp.com',
    storageBucket: 'poolschdule.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3jLai_EjD_yjCxGtpnLmIyllTueeOZDc',
    appId: '1:457062956823:android:2cb1ce7ab4596fab170152',
    messagingSenderId: '457062956823',
    projectId: 'poolschdule',
    storageBucket: 'poolschdule.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZF1KjQ3oJ8gNo1SYnnaTy9nmHz6WukkQ',
    appId: '1:457062956823:ios:90df7f5c55f4ec60170152',
    messagingSenderId: '457062956823',
    projectId: 'poolschdule',
    storageBucket: 'poolschdule.firebasestorage.app',
    iosBundleId: 'com.poolSchedule.poolschedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZF1KjQ3oJ8gNo1SYnnaTy9nmHz6WukkQ',
    appId: '1:457062956823:ios:90df7f5c55f4ec60170152',
    messagingSenderId: '457062956823',
    projectId: 'poolschdule',
    storageBucket: 'poolschdule.firebasestorage.app',
    iosBundleId: 'com.poolSchedule.poolschedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlciHDHkPqzO1k71z3zgqDiGISK7M11Fo',
    appId: '1:457062956823:web:163d3fe573786f53170152',
    messagingSenderId: '457062956823',
    projectId: 'poolschdule',
    authDomain: 'poolschdule.firebaseapp.com',
    storageBucket: 'poolschdule.firebasestorage.app',
  );

}